# Generated by Django 3.2 on 2021-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
