# Generated by Django 3.2.4 on 2021-06-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_item_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='item',
            new_name='items',
        ),
    ]
