# Generated by Django 3.2.4 on 2021-06-26 02:56

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Course = apps.get_model('backend', 'Course')
    Sequence = apps.get_model('backend', 'Sequence')
    for course in Course.objects.all():
        for i, item in enumerate(Course.members.all()):
            Sequence(
                item=item,
                course=course,
                order=i
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_sequence'),
    ]

    operations = [
    ]
