# Generated by Django 3.2.4 on 2021-06-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210625_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='items',
        ),
    ]
