# Generated by Django 3.2.4 on 2021-06-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_course_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='items',
            field=models.ManyToManyField(related_name='courses', through='backend.Sequence', to='backend.Item'),
        ),
    ]
