# Generated by Django 3.2 on 2021-06-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_dicussionpost_discussionpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
