# Generated by Django 3.2 on 2021-06-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_saveditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionpost',
            options={'ordering': ['time']},
        ),
    ]
