# Generated by Django 3.2 on 2021-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_discussionpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(null=True, to='backend.Item'),
        ),
    ]
